name: Build OpenWrt v6.x

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile v6.x Firmware inside Ubuntu 20.04
        run: |
          docker run --rm -v ${{ github.workspace }}:/build ubuntu:20.04 bash -c "
            set -e
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python2 python3 file ccache swig
            cd /build
            ./scripts/feeds update -a
            ./scripts/feeds install -a
            make defconfig
            make -j\$(nproc)
          "

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-wr840n-v6-firmware
          path: bin/targets/ramips/mt76x8/*.bin
